class USSDError(Exception):
    ...
    
class USSDRouteDoesNotExit(USSDError):
    ...
    
class USSDSessionTimeout(USSDError):
    ...
    
class USSDValidationError(USSDError):
    ...
    
class USSDInternalError(USSDError):
    ...